# Generated by Django 5.1.1 on 2024-10-05 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameExpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_player', models.BooleanField()),
                ('is_developer', models.BooleanField()),
                ('is_apply_news', models.BooleanField()),
                ('is_accepting_terms', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GameExpUser',
                'verbose_name_plural': 'GameExpUsers',
            },
        ),
    ]
